// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"demo-curd/api/v1"
	"demo-curd/config"
	"demo-curd/dao"
	"demo-curd/database"
	"demo-curd/i18n"
	"demo-curd/router"
	"demo-curd/service"
)

// Injectors from wire.go:

func InitApp() (App, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return App{}, err
	}
	databaseDatabase, err := database.NewDatabase(configConfig)
	if err != nil {
		return App{}, err
	}
	i18nI18n, err := i18n.NewI18n(configConfig)
	if err != nil {
		return App{}, err
	}
	routerRouter, err := router.NewRouterWithoutAuthMw(configConfig, i18nI18n)
	if err != nil {
		return App{}, err
	}
	curdDao := &dao.CurdDao{
		Db: databaseDatabase,
	}
	curdService := &service.CurdService{
		CurdDao: curdDao,
	}
	curdV1Api := &v1.CurdV1Api{
		CurdService: curdService,
	}
	app := App{
		Config:    configConfig,
		Database:  databaseDatabase,
		Router:    routerRouter,
		I18n:      i18nI18n,
		CurdV1Api: curdV1Api,
	}
	return app, nil
}
