version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "123456"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend

networks:
  backend:
    driver: bridge
