server:
  port: 8099

database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: ''
  dbname: go_gin
  maxIdleConns: 10
  maxOpenConns: 1000
  connMaxLifetime: 1h

jwt:
  realm: namnt.com
  signAlg: HS512
  secret: namnt@demo
  expiredTime: 999999h
  refreshExpTime: 999999h
  longRefreshExpTime: 999999h

resty:
  debug: true
  timeout: 1m

i18n:
  langs: vi,en

cors:
  allowOrigins: '*'
  allowMethods: '*'
  allowHeaders: Accept,Accept-Language,Origin,Content-Length,Content-Type,Authorization
  exposeHeaders: Content-Length,Content-Type
  allowCredentials: true
  maxAge: 24h

swagger:
  url:

security:
  authorizedRequests:
    - urls: /api/v1/**:*
      access: PermitAll
    - urls: /api/internal/**:*
      access: PermitAll

log:
  level: debug
