basePath: /
host: localhost:8099
info:
  contact:
    email: namnguyenthanh024@gmail.com
    name: Namnt
  description: This is Sample Service API.
  title: Sample Service API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
